version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees: ["guerda"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
